name: push

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: checkout source files
      uses: actions/checkout@v5
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: commit source files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: push source changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT_PUSH }}
        force: True
        repository: jzstraley/docsref
    - name: checkout site files
      uses: actions/checkout@v5
      with:
        ref: gh-pages
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: commit site files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: push site changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT_PUSH }}
        branch: gh-pages
        force: True
        repository: jzstraley/docsref